name: Publish Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - beta
          - alpha

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run type check
        run: npm run test:types
        
      - name: Run linting
        run: npm run test:lint
        
      - name: Run format check
        run: npm run test:format
        
      - name: Build package
        run: npm run build
        
      - name: Test package size
        run: npm run test:size

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build package
        run: npm run build
        
      - name: Test package
        run: npm run test
        
      - name: Pack and test
        run: npm run pack:test
        
      - name: Publish to NPM (Tag Release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Publish to NPM (Manual Release)
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.release_type }}" = "beta" ]; then
            npm run release:beta
          elif [ "${{ github.event.inputs.release_type }}" = "alpha" ]; then
            npm run release:alpha
          else
            npm run release:${{ github.event.inputs.release_type }}
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
  notify:
    needs: publish
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Notify success
        if: needs.publish.result == 'success'
        run: echo "🎉 Package published successfully!"
        
      - name: Notify failure
        if: needs.publish.result == 'failure'
        run: echo "❌ Package publishing failed!"